clean up

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -119,9 +119,11 @@ alias cp && unalias cp
 
 # Run emacs daemon
 pgrep emacs || emacs --daemon
-alias emax="emacsclient -t"                      # used to be "emacs -nw"
-alias semax="sudo emacsclient -t"                # used to be "sudo emacs -nw"
-alias emaxsc="emacsclient -c -a emacs"           # new - opens the GUI with alternate non-daemon
+alias emacs='emacs -nw'
+alias emax="emacsclient -nw"               # used to be "emacs -nw"
+alias semax="sudo emacsclient -nw"         # used to be "sudo emacs -nw"
+alias emaxsc="emacsclient -c -a emacs"     # new - opens the GUI with alternate non-daemon
+alias vim='emacsclient -nw'
 
 alias -s go='vim -O'
 alias -s rb='vim -O'
@@ -137,7 +139,7 @@ SAVEHIST=100000       # Remember about a years worth of history (AWESOME)
 HISTSIZE=100000
 
 # Custom stuff
-source ~/.aws_secrets.env
+#source ~/.aws_secrets.env
 source ~/bin/ccd
 source ~/bin/utils
 
@@ -147,90 +149,7 @@ ssh-add ~/.ssh/id_rsa
 ssh-add ~/.ssh/energis_ops_key
 ssh-add ~/.ssh/repricon_key
 ssh-add ~/.ssh/airtango.private_key
-
-# Linguistics and Paths
-
-# Android
-if [ -d "/opt/android-studio/" ] ; then
-  export PATH="$PATH:/opt/android-studio/bin"
-fi
-
-# Go
-export PATH=/usr/local/go/bin:$PATH
-export GOPATH=$HOME/go
-export PATH=$GOPATH/bin:$PATH
-
-# JS (Node)
-if [ -d "$HOME/.nvm" ] ; then
-  export NVM_DIR="$HOME/.nvm"
-  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
-fi
-
-# Python
-export PYTHONSTARTUP=~/.pystartup
-
-# Rust
-if [ -f "$HOME/.cargo/env" ] ; then
-  source $HOME/.cargo/env
-fi
-if [ -d "$HOME/.cargo/bin" ] ; then
-  export PATH="$HOME/.cargo/bin:$PATH"
-fi
-
-# set PATH so it includes user's private bin if it exists
-if [ -d "$HOME/bin" ] ; then
-  PATH="$HOME/bin:$PATH"
-  sh ~/bin/sigmaker.sh
-fi
-
-# Platform specifics
-if [[ "$PLATFORM" == 'OSX'  ]]; then
-  # SQL
-  export PSQLINST=/Applications/Postgres.app/Contents/Versions/10/bin
-  export PATH=$HOME/bin:$GOPATH/bin:$PATH:$PSQLINST
-  export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
-
-  # update paths for gnu coreutils
-  export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
-  export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
-
-  # set PATH to user macvim
-  if [ -d "/Applications/MacVim.app/Contents/bin" ] ; then
-    PATH="/Applications/MacVim.app/Contents/bin:$PATH"
-  fi
-
-  # set PATH to user maxTex
-  if [ -d "/Library/TeX/texbin" ] ; then
-    export PATH="/Library/TeX/texbin":$PATH
-  fi
-
-  export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"
-else
-  setxkbmap -option compose:ralt || echo "Couldn't set the compose key"
-fi
-
-# Rvm, Ruby
-# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
-if [ -d "$HOME/.rvm" ] ; then
-  export PATH="$PATH:$HOME/.rvm/bin"
-fi
-
-# Add Anaconda stuff
-if [ -d "/opt/anaconda3" ] ; then
-  export PATH="$PATH:/opt/anaconda3/bin"
-fi
-
-# Add firefox stuff
-if [ -d "/opt/firefox" ] ; then
-  export PATH="/opt/firefox:$PATH"
-fi
-
-# Mark it loaded
-export ZSHLOADED=YES
-
-alias yarn='echo "You are right, NOT"'
-export DB_USERNAME=sands
+ssh-add ~/.ssh/energis-prd-ops.pem
 
 export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
 export FZF_DEFAULT_COMMAND='
@@ -238,19 +157,21 @@ export FZF_DEFAULT_COMMAND='
    find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
       sed s/^..//) 2> /dev/null'
 export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 
-# The next line updates PATH for the Google Cloud SDK.
-if [ -f '/Users/sands/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/sands/Downloads/google-cloud-sdk/path.zsh.inc'; fi
+sh -x /home/sillyfellow/.config/i3/natural_scrolling.sh
 
-# The next line enables shell command completion for gcloud.
-if [ -f '/Users/sands/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/sands/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
+export GTK_IM_MODULE=ibus
+export XMODIFIERS=@im=ibus
+export QT_IM_MODULE=ibus
 
-if [ -d "$HOME/.pyenv" ] ; then
-    export PYENV_ROOT="$HOME/.pyenv"
-    export PATH="$PYENV_ROOT/bin:$PATH"
-    if command -v pyenv 1>/dev/null 2>&1; then
-        eval "$(pyenv init -)"
-    fi
+setxkbmap -option compose:ralt || echo "Couldn't set the compose key"
+source ~/.aliases
+
+[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
+if command -v pyenv 1>/dev/null 2>&1; then
+    eval "$(pyenv init -)"
 fi
 
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+# Mark it loaded
+export ZSHLOADED=YES
